site_name: ZJUBCA Blockchain Roadmap
nav:
    - 学习路径: index.md
    - 技术分享:
          - 分层确定性钱包初探: tech/Hierarchical_Deterministic_Wallets/Hierarchical_Deterministic_Wallets.md
          - 以太坊智能合约初探: tech/Ethereum_Smart_Contract_Introduction/Ethereum_Smart_Contract_Introduction.md
          - Fluence 空投代码分析: tech/fluence/fluence.md
          - Solana和Aptos技术对比浅析: tech/A_brief_technical_analysis_of_solana_and_move/A_brief_technical_analysis_of_solana_and_move.md
          - 代币经济学: tech/Tokenomic/Tokenomic.pdf
          - 预言机浅析:对比Pyth和Chainlink: tech/Comparison_of_Pyth_and_Chainlink/Comparison_of_Pyth_and_Chainlink.md
          - 如何与未开源合约进行交互: tech/How_to_interact_with_unopen_source_contract/How_to_interact_with_unopen_source_contract.pdf
    - 每周精选: weekly/weekly.md
    - ETH:
          - 学习路径: eth/eth.md
          - 开发教程: eth/eth_dapp.md
    - Base:
          - 介绍: base/base_intro.md
          - Farcaster: base/base_farcaster.md
          - Degen: base/base_degen.md
    - Ton: ton/ton.md
    - NFT: nft/nft.md
    - 联盟链: consortium/consortium.md
    - 参考文档: reference/reference.md
    - 历史文件: history/history.md
#主题
theme:
    name: "material"
    language: "zh" # 配置语言
    palette: # 颜色
        primary: "black"
        accent: "indigo"
    feature:
        tabs: true # 横向导航

markdown_extensions:
    - admonition # 提示块
    - footnotes # 脚注
    - meta # 定义元数据，通过文章上下文控制，如disqus
    - pymdownx.caret # 下划线上标
    - pymdownx.tilde # 删除线下标
    - pymdownx.critic # 增加删除修改高亮注释，可修饰行内或段落
    - pymdownx.details # 提示块可折叠
    - pymdownx.inlinehilite # 行内代码高亮
    - pymdownx.mark # 文本高亮
    - pymdownx.smartsymbols # 符号转换
    - pymdownx.superfences # 代码嵌套在列表里
    - codehilite: # 代码高亮，显示行号
          guess_lang: false
          linenums: true
    - toc: # 锚点
          permalink: true
    #  - pymdownx.arithmatex  # 数学公式
    - pymdownx.betterem: # 对加粗和斜体更好的检测
          smart_enable: all
    #  - pymdownx.emoji:  # 表情
    #      emoji_generator: !!python/name:pymdownx.emoji.to_svg
    #  - pymdownx.magiclink  # 自动识别超链接
    - pymdownx.tasklist: # 复选框checklist
          custom_checkbox: true

# PDF导出插件
plugins:
    - search
#  - pdf-export #这个插件还有点问题，没有更新
